### ISSUE TITLE
Log levels (severities) not forwarded to StackDriver

### ISSUE THREAD

**Issue by ttencate** [aprilabank/journaldriver#11]
Journald annotates log messages by priority (0/emerg through 7/debug, see "man journald" for details). The StackDriver logs viewer (https://console.cloud.google.com/logs/viewer) supports filtering by log level (critical, error, warning, info, debug). But none of the log messages from journaldriver seem to have a level assigned.

All that needs to be done is pass journald's priority level into the `severity` field of the [`LogEntry` object](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) in the API.

I might take a quick stab at this, but I don't really know Rust, so I'll let you know how it turns out.

**Comment by tazjin** [comment]
@ttencate Thanks for opening the issue!

The thing about `journald` severities is that most applications logging to `journald` aren't setting them at all. I suppose from the perspective of journaldriver it would make the most sense that the severity levels of `journald` are mapped to the corresponding StackDriver levels, but I'm not sure if applications that aren't logging via the `journald`-API can make use of those :thinking:

Either way,

> but I don't really know Rust, so I'll let you know how it turns out

Feel free to ping me here or on IRC (tazjin @ freenode) if you run into any issues. As a starting point, the representation of journal entries in the journald API is a simple `<String, String>` map (see [here](https://docs.rs/systemd/0.3.0/systemd/journal/type.JournalRecord.html)). In journaldriver this is parsed and transformed into a StackDriver record in the [implementation of `From<JournalRecord>`](https://github.com/aprilabank/journaldriver/blob/master/src/main.rs#L356) for `LogEntry`.

**Comment by tazjin** [comment]
> but I'm not sure if applications that aren't logging via the journald-API can make use of those :thinking: 

Turns out they can, via a magic syntax of enclosing the numeric priority in `<>` at the beginning of log output. Open question for this is whether this priority is then removed from the log entry payload itself, because if it isn't the JSON-parsing in journaldriver would fail. I'll check this.

**Comment by tazjin** [comment]
Alright, seems like that's exactly what we'd want.

The levels and their log format are [defined here](http://0pointer.de/public/systemd-man/sd-daemon.html) and according to [this](http://0pointer.de/public/systemd-man/systemd.exec.html#SyslogLevelPrefix=) ...

> log lines written by the executed process that are prefixed with a log level will be passed on to syslog with this log level set **but the prefix removed**.

**Comment by tazjin** [comment]
> Right now I don't really care how these severities go into journald, I just care how they are coming out :)

:ok_hand: 

I'll take a look at the PR!

**Comment by tazjin** [comment]
Great! I'm adding it to our primary Rust service at the moment with a simple decorator for `log4rs`-encoders. For reference, for people from the future who stumble upon this issue:

```rust
/// Implementation of a log-encoder decorator that can prepend
/// journald log priorities to any given `log4rs`-encoder.
#[derive(Debug)]
struct JournaldDecorator<E: Encode>(E);

/// Helper function to map from `log`-crate log levels to journald log
/// priorites. Please see `sd-daemon(3)` for detailed information on
/// these levels.
fn journald_priority(level: &Level) -> &'static str {
    match level {
        Level::Error => "<3>",
        Level::Warn  => "<4>",
        Level::Info  => "<6>",
        // journald & stackdriver do not differentiate between 'Debug'
        // and higher levels, so debug and trace are both mapped to
        // `SD_DEBUG`.
        Level::Debug => "<7>",
        Level::Trace => "<7>",
    }
}

impl <E: Encode> Encode for JournaldDecorator<E> {
    fn encode(&self, w: &mut Write, record: &Record)
              -> Result<(), Box<Error + Sync + Send>> {
        // First write the journald priority, then delegate to the
        // decorated encoder.
        write!(w, "{}", journald_priority(&record.level()))?;
        self.0.encode(w, record)
    }
}
```
